// Auto-generated by scripts/generate-client-logos.mjs — do not edit manually.
export const CLIENT_LOGO_BASE_PATH = '/DATA_EVENTSHOOT/SITE_IMAGES/OPDRACHTGEVERS'

export interface ClientLogo {
  file: string
  name: string
}

export const CLIENT_LOGOS: ClientLogo[] = [
  {
    "file": "beelegal.png",
    "name": "BeeLegal"
  },
  {
    "file": "blubillywig.png",
    "name": "Blue Billywig"
  },
  {
    "file": "dell.png",
    "name": "Dell"
  },
  {
    "file": "dsr.png",
    "name": "DSR"
  },
  {
    "file": "dux.png",
    "name": "Dux"
  },
  {
    "file": "gbl.png",
    "name": "GBL Alliance"
  },
  {
    "file": "gladwell.png",
    "name": "Gladwell Academy"
  },
  {
    "file": "ITChannelpro.png",
    "name": "IT Channel Pro"
  },
  {
    "file": "koers.png",
    "name": "Koers"
  },
  {
    "file": "obeya.png",
    "name": "Obeya"
  },
  {
    "file": "s2grupo.png",
    "name": "S2Grupo"
  },
  {
    "file": "vectocon.png",
    "name": "Vectocon"
  }
]
