// Auto-generated by scripts/generate-faq-data.mjs — do not edit manually.
import type { FaqPageKey } from '@/lib/faqPages'
import type { SanitySiteFaqItem } from '@/lib/sanity'

type FaqLangMap = Record<'nl' | 'en', SanitySiteFaqItem[]>

export const siteFaqByPage: Record<FaqPageKey, FaqLangMap> = {
  "home": {
    "nl": [
      {
        "_id": "faq-home-1",
        "question": "Wat levert professionele eventcontent concreet op na mijn event?",
        "answer": "Eén event levert 25+ kant-en-klare items op: foto's, aftermovies en interviews in de formaten die je marketeer direct kan plaatsen. Je haalt maanden content uit één productiedag, terwijl het event nog vers in het geheugen zit."
      },
      {
        "_id": "faq-home-2",
        "question": "Voor welke soorten events werkt Eventshoot.nl het best?",
        "answer": "Eventshoot.nl is gespecialiseerd in zakelijke events: congressen, conferenties, ledendagen, seminars en bedrijfsbijeenkomsten. Informele feesten en consumentenevents vallen buiten onze focus."
      },
      {
        "_id": "faq-home-3",
        "question": "Hoe snel is de content klaar na afloop?",
        "answer": "Standaard binnen 48 uur na het event. Same-day levering is mogelijk als add-on. Zo kan je marketeer posten terwijl deelnemers het event nog bespreken op LinkedIn."
      },
      {
        "_id": "faq-home-4",
        "question": "Gebruikt Eventshoot.nl AI voor de beelden?",
        "answer": "Nee. Alles wat je krijgt is echt opgenomen op jouw event, met echte mensen en professionele apparatuur. AI wordt alleen gebruikt in de nabewerking, zoals selectie, transcriptie en ondertiteling."
      },
      {
        "_id": "faq-home-5",
        "question": "Moet mijn organisatie iemand hebben die de content uitrolt?",
        "answer": "Ja, dat werkt het best. Eventshoot.nl produceert, jij plaatst. Een marketeer, communicatiemedewerker of social media-manager die de content op LinkedIn, je website en in je nieuwsbrief zet, is de ideale fit."
      },
      {
        "_id": "faq-home-6",
        "question": "Werken jullie door heel Nederland?",
        "answer": "Ja. Eventshoot.nl is actief door heel Nederland. Reis- en transportkosten worden separaat berekend en vooraf besproken."
      }
    ],
    "en": [
      {
        "_id": "faq-home-1",
        "question": "What does professional event content deliver after my event?",
        "answer": "One event yields 25+ ready-to-use items: photos, aftermovies and interviews in formats your marketing team can publish directly. You get months of content from a single production day, while the event is still top of mind."
      },
      {
        "_id": "faq-home-2",
        "question": "Which types of events is Eventshoot.nl best suited for?",
        "answer": "Eventshoot.nl specialises in corporate events: congresses, conferences, member days, seminars and business meetings. Informal parties and consumer events are outside our focus."
      },
      {
        "_id": "faq-home-3",
        "question": "How quickly is the content ready after the event?",
        "answer": "Standard delivery within 48 hours after the event. Same-day delivery is available as an add-on. Your marketing team can post while attendees are still discussing the event on LinkedIn."
      },
      {
        "_id": "faq-home-4",
        "question": "Does Eventshoot.nl use AI for the visuals?",
        "answer": "No. Everything you receive is genuinely recorded at your event, with real people and professional equipment. AI is only used in post-production, such as selection, transcription and subtitling."
      },
      {
        "_id": "faq-home-5",
        "question": "Does my organisation need someone to publish the content?",
        "answer": "Yes, that works best. Eventshoot.nl produces, you publish. A marketer, communications officer or social media manager who posts on LinkedIn, your website and newsletter is the ideal fit."
      },
      {
        "_id": "faq-home-6",
        "question": "Do you work throughout the Netherlands?",
        "answer": "Yes. Eventshoot.nl is active throughout the Netherlands. Travel and transport costs are calculated separately and discussed in advance."
      }
    ]
  },
  "kennismaken": {
    "nl": [
      {
        "_id": "faq-kennismaken-1",
        "question": "Hoe snel reageert Rolf?",
        "answer": "Doorgaans binnen een paar uur op werkdagen. Rolf reageert persoonlijk, geen callcenter."
      },
      {
        "_id": "faq-kennismaken-2",
        "question": "Wat kost een kennismaking?",
        "answer": "Een kennismaking is gratis en vrijblijvend. Geen verplichtingen."
      },
      {
        "_id": "faq-kennismaken-3",
        "question": "Kan ik ook last-minute boeken?",
        "answer": "Bel direct: 06 251 777 28. Rolf probeert altijd iets te regelen als de agenda het toelaat."
      },
      {
        "_id": "faq-kennismaken-4",
        "question": "Wat gebeurt er tijdens een kennismaking van 20 minuten?",
        "answer": "We bespreken je event, doelgroep, gewenste content en welk pakket past. Daarna weet je of we elkaar liggen en wat de vervolgstap is."
      },
      {
        "_id": "faq-kennismaken-5",
        "question": "Kan ik een checklist of onepager downloaden?",
        "answer": "Ja. Op de homepage kun je een content checklist downloaden. Tijdens de kennismaking stuur ik je ook graag de onepager met pakketten en werkwijze toe."
      },
      {
        "_id": "faq-kennismaken-6",
        "question": "Werkt Rolf door heel Nederland?",
        "answer": "Ja, Eventshoot.nl is actief door heel Nederland. Reiskosten worden separaat berekend."
      }
    ],
    "en": [
      {
        "_id": "faq-kennismaken-1",
        "question": "How quickly does Rolf respond?",
        "answer": "Usually within a few hours on working days. Rolf responds personally, no call centre."
      },
      {
        "_id": "faq-kennismaken-2",
        "question": "How much does an introductory call cost?",
        "answer": "An introductory call is free and without obligation. No commitments."
      },
      {
        "_id": "faq-kennismaken-3",
        "question": "Can I book last-minute?",
        "answer": "Call directly: +31 6 251 777 28. Rolf always tries to arrange something if the calendar allows."
      },
      {
        "_id": "faq-kennismaken-4",
        "question": "What happens during a 20-minute introductory call?",
        "answer": "We discuss your event, audience, desired content and which package fits. Afterwards you know if we are a good match and what the next step is."
      },
      {
        "_id": "faq-kennismaken-5",
        "question": "Can I download a checklist or one-pager?",
        "answer": "Yes. On the homepage you can download a content checklist. During the introductory call I am happy to send you the one-pager with packages and workflow."
      },
      {
        "_id": "faq-kennismaken-6",
        "question": "Does Rolf work throughout the Netherlands?",
        "answer": "Yes, Eventshoot.nl is active throughout the Netherlands. Travel costs are calculated separately."
      }
    ]
  },
  "eventfotografie": {
    "nl": [
      {
        "_id": "faq-eventfotografie-1",
        "question": "Hoeveel foto's ontvang ik na een event?",
        "answer": "Afhankelijk van het pakket ontvang je 100 tot 300 bewerkte foto's. Het Highlight-pakket levert 100–150 foto's, Headline 150–200 en Heroes 200–300. Allemaal kant-en-klaar voor direct gebruik."
      },
      {
        "_id": "faq-eventfotografie-2",
        "question": "In welke formaten worden de foto's geleverd?",
        "answer": "Horizontaal voor je website, 4:5 voor LinkedIn en verticaal voor Stories en Reels. Je marketeer hoeft niets meer bij te snijden of te formatteren."
      },
      {
        "_id": "faq-eventfotografie-3",
        "question": "Valt de fotograaf op tijdens het event?",
        "answer": "Nee. Rolf werkt discreet en zelfstandig. Hij kent het programma, stemt vooraf af met locatie en techniek, en legt de sleutelmomenten vast zonder in de weg te lopen."
      },
      {
        "_id": "faq-eventfotografie-4",
        "question": "Kunnen jullie ook een groepsfoto regelen?",
        "answer": "Ja. Groepsfoto-momenten worden vooraf afgestemd, inclusief timing en locatie op het programma. Rolf schakelt makkelijk tussen technici en directiekamer."
      },
      {
        "_id": "faq-eventfotografie-5",
        "question": "Wat als het podium donker is of de slides slecht leesbaar zijn?",
        "answer": "Dat bespreken we vooraf met locatie en techniek. Backdrop, podiumlicht en presentatieformat worden doorgenomen voordat de eerste gast binnenkomt. Geen toeval, wel verschil."
      },
      {
        "_id": "faq-eventfotografie-6",
        "question": "Kan ik foto en video combineren in één opdracht?",
        "answer": "Ja. De pakketten Headline en Heroes combineren foto en video standaard. Liever alleen foto? Dat kan ook. Bekijk de pakketten op de tarievenpagina of plan een kennismaking."
      }
    ],
    "en": [
      {
        "_id": "faq-eventfotografie-1",
        "question": "How many photos do I receive after an event?",
        "answer": "Depending on the package you receive 100 to 300 edited photos. The Highlight package delivers 100–150 photos, Headline 150–200 and Heroes 200–300. All ready for immediate use."
      },
      {
        "_id": "faq-eventfotografie-2",
        "question": "In which formats are the photos delivered?",
        "answer": "Horizontal for your website, 4:5 for LinkedIn and vertical for Stories and Reels. Your marketing team does not need to crop or reformat anything."
      },
      {
        "_id": "faq-eventfotografie-3",
        "question": "Is the photographer obtrusive during the event?",
        "answer": "No. Rolf works discreetly and independently. He knows the programme, aligns with the venue and AV team in advance, and captures key moments without getting in the way."
      },
      {
        "_id": "faq-eventfotografie-4",
        "question": "Can you also arrange a group photo?",
        "answer": "Yes. Group photo moments are agreed in advance, including timing and location on the programme. Rolf moves easily between technical staff and boardroom level."
      },
      {
        "_id": "faq-eventfotografie-5",
        "question": "What if the stage is dark or slides are hard to read?",
        "answer": "We discuss this in advance with the venue and AV team. Backdrop, stage lighting and presentation format are reviewed before the first guest arrives. No guesswork."
      },
      {
        "_id": "faq-eventfotografie-6",
        "question": "Can I combine photo and video in one assignment?",
        "answer": "Yes. The Headline and Heroes packages combine photo and video as standard. Prefer photo only? That is possible too. See the packages on the pricing page or schedule an introductory call."
      }
    ]
  },
  "eventvideo": {
    "nl": [
      {
        "_id": "faq-eventvideo-1",
        "question": "Welke soorten eventvideo's maakt Eventshoot.nl?",
        "answer": "Social aftermovies (45–90 sec voor LinkedIn), corporate aftermovies (90–180 sec voor je website), event interviews met sprekers en deelnemers, en event promotievideo's voor de volgende editie."
      },
      {
        "_id": "faq-eventvideo-2",
        "question": "Hoe lang duurt een aftermovie?",
        "answer": "De social aftermovie duurt 45–90 seconden, ideaal voor LinkedIn. Het Headline- en Heroes-pakket leveren daarnaast een corporate aftermovie van 90–180 seconden voor je website."
      },
      {
        "_id": "faq-eventvideo-3",
        "question": "Zitten ondertitels standaard inbegrepen?",
        "answer": "Ja. AI-ondertiteling zit in alle pakketten inbegrepen. Human ondertiteling (98% correct) is beschikbaar als add-on voor Headline en Heroes."
      },
      {
        "_id": "faq-eventvideo-4",
        "question": "Hoeveel interviews kan ik verwachten?",
        "answer": "In het Headline-pakket 10–15 één-camera interviews, in Heroes 25–30. Ideaal voor quotes op LinkedIn en content voor je volgende editie."
      },
      {
        "_id": "faq-eventvideo-5",
        "question": "Kan ik de video dezelfde dag nog online zetten?",
        "answer": "Ja, same-day levering is mogelijk als add-on (vanaf € 425 afhankelijk van pakket). Handig als je direct na afloop wilt posten op social media."
      },
      {
        "_id": "faq-eventvideo-6",
        "question": "Wie bepaalt wat er in de video komt?",
        "answer": "Dat stemmen we vooraf af in de pre-production meeting. Jij geeft aan welke momenten, sprekers en sfeer belangrijk zijn. Daarna werkt Rolf zelfstandig op locatie."
      }
    ],
    "en": [
      {
        "_id": "faq-eventvideo-1",
        "question": "What types of event videos does Eventshoot.nl produce?",
        "answer": "Social aftermovies (45–90 sec for LinkedIn), corporate aftermovies (90–180 sec for your website), event interviews with speakers and attendees, and event promo videos for the next edition."
      },
      {
        "_id": "faq-eventvideo-2",
        "question": "How long is an aftermovie?",
        "answer": "The social aftermovie runs 45–90 seconds, ideal for LinkedIn. The Headline and Heroes packages also include a corporate aftermovie of 90–180 seconds for your website."
      },
      {
        "_id": "faq-eventvideo-3",
        "question": "Are subtitles included as standard?",
        "answer": "Yes. AI subtitling is included in all packages. Human subtitling (98% accuracy) is available as an add-on for Headline and Heroes."
      },
      {
        "_id": "faq-eventvideo-4",
        "question": "How many interviews can I expect?",
        "answer": "The Headline package includes 10–15 single-camera interviews, Heroes 25–30. Ideal for LinkedIn quotes and content for your next edition."
      },
      {
        "_id": "faq-eventvideo-5",
        "question": "Can I publish the video on the same day?",
        "answer": "Yes, same-day delivery is available as an add-on (from € 425 depending on package). Useful if you want to post on social media immediately after the event."
      },
      {
        "_id": "faq-eventvideo-6",
        "question": "Who decides what goes into the video?",
        "answer": "We align this in advance during the pre-production meeting. You indicate which moments, speakers and atmosphere matter. Rolf then works independently on site."
      }
    ]
  },
  "tarieven": {
    "nl": [
      {
        "_id": "faq-tarieven-1",
        "question": "Wat kosten de pakketten?",
        "answer": "Highlight € 825 (4 uur), Headline € 2.250 (8 uur, meest gekozen) en Heroes € 3.450 (10 uur, foto + video). Alle prijzen excl. BTW. Reis- en transportkosten separaat."
      },
      {
        "_id": "faq-tarieven-2",
        "question": "Wat zit standaard inbegrepen bij elk pakket?",
        "answer": "Een online pre-production meeting, post-production met één correctieronde en AI-ondertiteling op video's (met controle op naamweergave). Reisuren, reis- en transportkosten en btw komen daar bovenop."
      },
      {
        "_id": "faq-tarieven-3",
        "question": "Zitten reiskosten in de prijs?",
        "answer": "Nee. Reis- en transportkosten worden separaat berekend en vooraf besproken. Eventshoot.nl werkt door heel Nederland."
      },
      {
        "_id": "faq-tarieven-4",
        "question": "Wat zijn de add-ons?",
        "answer": "Same-day levering (€ 425 / € 650 / € 925), human ondertiteling € 13 per minuut (Headline/Heroes), en event promotievideo op offerte."
      },
      {
        "_id": "faq-tarieven-5",
        "question": "Zit een correctieronde inbegrepen?",
        "answer": "Ja. Post-production met één correctieronde zit in alle pakketten inbegrepen."
      },
      {
        "_id": "faq-tarieven-6",
        "question": "Hoe kies ik het juiste pakket?",
        "answer": "Highlight past bij kleinere events en social-only. Headline is de standaard voor een jaarcongres of ledendag. Heroes is voor hoog-profile congressen met foto én video. Twijfel? Plan een gratis kennismaking van 20 minuten."
      }
    ],
    "en": [
      {
        "_id": "faq-tarieven-1",
        "question": "What do the packages cost?",
        "answer": "Highlight € 825 (4 hours), Headline € 2,250 (8 hours, most popular) and Heroes € 3,450 (10 hours, photo + video). All prices excl. VAT. Travel and transport costs separate."
      },
      {
        "_id": "faq-tarieven-2",
        "question": "What is included as standard in every package?",
        "answer": "An online pre-production meeting, post-production with one revision round and AI subtitling on videos (with name display checks). Travel time, travel and transport costs and VAT are additional."
      },
      {
        "_id": "faq-tarieven-3",
        "question": "Are travel costs included in the price?",
        "answer": "No. Travel and transport costs are calculated separately and discussed in advance. Eventshoot.nl works throughout the Netherlands."
      },
      {
        "_id": "faq-tarieven-4",
        "question": "What are the add-ons?",
        "answer": "Same-day delivery (€ 425 / € 650 / € 925), human subtitling € 13 per minute (Headline/Heroes), and event promo video on quote."
      },
      {
        "_id": "faq-tarieven-5",
        "question": "Is a revision round included?",
        "answer": "Yes. Post-production with one revision round is included in all packages."
      },
      {
        "_id": "faq-tarieven-6",
        "question": "How do I choose the right package?",
        "answer": "Highlight suits smaller events and social-only. Headline is the standard for an annual congress or member day. Heroes is for high-profile congresses with photo and video. Unsure? Schedule a free 20-minute introductory call."
      }
    ]
  },
  "over-rolf": {
    "nl": [
      {
        "_id": "faq-over-rolf-1",
        "question": "Wie is Rolf Trijber?",
        "answer": "Rolf Trijber is eventfotograaf en videograaf met 40+ jaar ervaring in beeldproductie. Hij is gespecialiseerd in zakelijke events door heel Nederland: congressen, conferenties, ledendagen en bedrijfsbijeenkomsten."
      },
      {
        "_id": "faq-over-rolf-2",
        "question": "Werk je alleen of met een team?",
        "answer": "Rolf is je vaste aanspreekpunt en regisseur op locatie. Voor grotere congressen schakelt hij een vast netwerk van freelancers in: second shooters, videografen en assistenten. Jij hebt één contactpersoon, de productie schaal je mee."
      },
      {
        "_id": "faq-over-rolf-3",
        "question": "Waarom kiezen klanten voor langetermijnsamenwerking?",
        "answer": "Eventshoot.nl is gebouwd op vaste relaties, niet op eenmalige klussen. Klanten zoals GBL Alliance werken al jaren samen met Rolf. Doorlopende stijl, kennis van je event en meedenken over opzet en vormgeving maken elk jaar het beeld sterker."
      },
      {
        "_id": "faq-over-rolf-4",
        "question": "Wat maakt Rolf anders dan een jonge eventfotograaf?",
        "answer": "Veertig jaar productie-ervaring zit ingebakken in wat je krijgt. Geen onzekere handen, geen gemiste momenten. Plus het sociale gemak om te schakelen tussen technici en directiekamer."
      },
      {
        "_id": "faq-over-rolf-5",
        "question": "Ben je ook grafisch vormgever?",
        "answer": "Ja, Rolf is van origine grafisch vormgever. Compositie, kleur en typografie zitten in elk beeld dat je ontvangt, of het nu een foto, aftermovie of interview is."
      },
      {
        "_id": "faq-over-rolf-6",
        "question": "Hoe neem ik contact op met Rolf?",
        "answer": "Bel 06 251 777 28, mail rolf@eventshoot.nl of plan een kennismaking via de contactpagina. Rolf reageert persoonlijk, geen callcenter."
      }
    ],
    "en": [
      {
        "_id": "faq-over-rolf-1",
        "question": "Who is Rolf Trijber?",
        "answer": "Rolf Trijber is an event photographer and videographer with 40+ years of experience in visual production. He specialises in corporate events throughout the Netherlands: congresses, conferences, member days and business meetings."
      },
      {
        "_id": "faq-over-rolf-2",
        "question": "Do you work alone or with a team?",
        "answer": "Rolf is your fixed point of contact and director on site. For larger congresses he brings in a trusted network of freelancers: second shooters, videographers and assistants. You have one contact person, production scales with your event."
      },
      {
        "_id": "faq-over-rolf-3",
        "question": "Why do clients choose long-term collaboration?",
        "answer": "Eventshoot.nl is built on lasting relationships, not one-off jobs. Clients such as GBL Alliance have worked with Rolf for years. Consistent style, knowledge of your event and input on setup and design make the visuals stronger every year."
      },
      {
        "_id": "faq-over-rolf-4",
        "question": "What makes Rolf different from a young event photographer?",
        "answer": "Forty years of production experience is built into what you receive. No uncertain hands, no missed moments. Plus the social ease to switch between technical staff and the boardroom."
      },
      {
        "_id": "faq-over-rolf-5",
        "question": "Are you also a graphic designer?",
        "answer": "Yes, Rolf originally trained as a graphic designer. Composition, colour and typography are present in every visual you receive, whether photo, aftermovie or interview."
      },
      {
        "_id": "faq-over-rolf-6",
        "question": "How do I contact Rolf?",
        "answer": "Call +31 6 251 777 28, email rolf@eventshoot.nl or schedule an introductory call via the contact page. Rolf responds personally, no call centre."
      }
    ]
  },
  "voor-brancheverenigingen": {
    "nl": [
      {
        "_id": "faq-voor-brancheverenigingen-1",
        "question": "Wij organiseren maar twee events per jaar. Is dat genoeg voor een samenwerking?",
        "answer": "Jazeker. Eventshoot.nl werkt ook voor verenigingen met minder frequente events. We bespreken vooraf wat je nodig hebt en stemmen het aanbod daarop af."
      },
      {
        "_id": "faq-voor-brancheverenigingen-2",
        "question": "Kunnen jullie content leveren die onze ledenwerving ondersteunt?",
        "answer": "Ja. Professionele beelden van echte ledendagen en jaarcongressen laten zien wat lidmaatschap waard is. Foto's en video's zijn klaar voor je website, nieuwsbrief en social media."
      },
      {
        "_id": "faq-voor-brancheverenigingen-3",
        "question": "Kunnen jullie ook interviews met sprekers of leden verzorgen?",
        "answer": "Ja. Op aanvraag verzorg ik korte interviewopnames met sprekers, bestuurders of leden, als aanvulling op de eventreportage."
      },
      {
        "_id": "faq-voor-brancheverenigingen-4",
        "question": "Hoe snel ontvangen we het materiaal na ons jaarcongres?",
        "answer": "Standaard binnen 48 uur. Same-day levering is ook mogelijk, ideaal als je snel iets op social media wilt zetten terwijl het congres nog trending is."
      },
      {
        "_id": "faq-voor-brancheverenigingen-5",
        "question": "Werken jullie samen met onze vaste AV-partner op locatie?",
        "answer": "Ja. Backdrop, podiumlicht, presentatieformat en interviewlocatie worden vooraf afgestemd met techniek. Rolf schakelt soepel met technische teams."
      },
      {
        "_id": "faq-voor-brancheverenigingen-6",
        "question": "Wat als ons budget beperkt is?",
        "answer": "Neem contact op voor een eerlijk gesprek. Ik denk graag mee in wat haalbaar is, zodat je toch professionele content overhoudt van je belangrijkste event."
      }
    ],
    "en": [
      {
        "_id": "faq-voor-brancheverenigingen-1",
        "question": "We only organise two events per year. Is that enough for a partnership?",
        "answer": "Absolutely. Eventshoot.nl also works with associations that hold events less frequently. We discuss your needs in advance and tailor the offer."
      },
      {
        "_id": "faq-voor-brancheverenigingen-2",
        "question": "Can you deliver content that supports our member recruitment?",
        "answer": "Yes. Professional visuals from real member days and annual congresses show the value of membership. Photos and videos are ready for your website, newsletter and social media."
      },
      {
        "_id": "faq-voor-brancheverenigingen-3",
        "question": "Can you also conduct interviews with speakers or members?",
        "answer": "Yes. On request I produce short interview recordings with speakers, board members or members, as a supplement to the event coverage."
      },
      {
        "_id": "faq-voor-brancheverenigingen-4",
        "question": "How quickly do we receive the material after our annual congress?",
        "answer": "Standard delivery within 48 hours. Same-day delivery is also possible, ideal if you want to post on social media while the congress is still trending."
      },
      {
        "_id": "faq-voor-brancheverenigingen-5",
        "question": "Do you work with our regular AV partner on site?",
        "answer": "Yes. Backdrop, stage lighting, presentation format and interview location are agreed in advance with the AV team. Rolf works smoothly with technical crews."
      },
      {
        "_id": "faq-voor-brancheverenigingen-6",
        "question": "What if our budget is limited?",
        "answer": "Get in touch for an honest conversation. I am happy to think along about what is feasible, so you still get professional content from your most important event."
      }
    ]
  },
  "voor-eventbureaus": {
    "nl": [
      {
        "_id": "faq-voor-eventbureaus-1",
        "question": "Kunnen jullie als vaste content-partner achter de schermen werken?",
        "answer": "Ja. Eventshoot.nl is gebouwd voor bureaus die een betrouwbare partner zoeken event na event. Ik lees het runsheet, werk zelfstandig en lever wat jij en je klant nodig hebben."
      },
      {
        "_id": "faq-voor-eventbureaus-2",
        "question": "Leveren jullie white-label, zonder Eventshoot.nl branding?",
        "answer": "Ja. Op aanvraag lever ik content zonder eigen branding, zodat je het onder de naam van jouw bureau aan je klant kunt presenteren."
      },
      {
        "_id": "faq-voor-eventbureaus-3",
        "question": "Hoe kort van tevoren kunnen jullie ingepland worden?",
        "answer": "Dat hangt van de agenda af. Neem zo vroeg mogelijk contact op, maar bel gerust last-minute: 06 251 777 28. Ik doe mijn best als het kan."
      },
      {
        "_id": "faq-voor-eventbureaus-4",
        "question": "Moet ik een uitgebreide briefing schrijven?",
        "answer": "Nee. Een kort vooroverleg en het runsheet zijn meestal genoeg. Ik snap hoe de eventwereld werkt en vind mijn weg op locatie."
      },
      {
        "_id": "faq-voor-eventbureaus-5",
        "question": "Kunnen jullie same-day highlights leveren voor de klant?",
        "answer": "Ja. Same-day levering is beschikbaar als add-on. Ideaal als je klant direct na afloop content wil op social media."
      },
      {
        "_id": "faq-voor-eventbureaus-6",
        "question": "Werken jullie ook buiten Nederland?",
        "answer": "Ja. Ik werk door heel Nederland en op aanvraag ook in het buitenland. Reiskosten worden separaat berekend."
      }
    ],
    "en": [
      {
        "_id": "faq-voor-eventbureaus-1",
        "question": "Can you work as a fixed content partner behind the scenes?",
        "answer": "Yes. Eventshoot.nl is built for agencies looking for a reliable partner event after event. I read the run sheet, work independently and deliver what you and your client need."
      },
      {
        "_id": "faq-voor-eventbureaus-2",
        "question": "Do you deliver white-label, without Eventshoot.nl branding?",
        "answer": "Yes. On request I deliver content without my own branding, so you can present it to your client under your agency name."
      },
      {
        "_id": "faq-voor-eventbureaus-3",
        "question": "How late can you still be booked?",
        "answer": "That depends on the calendar. Contact me as early as possible, but call for last-minute requests: +31 6 251 777 28. I do my best when it is possible."
      },
      {
        "_id": "faq-voor-eventbureaus-4",
        "question": "Do I need to write an extensive briefing?",
        "answer": "No. A short pre-meeting and the run sheet are usually enough. I understand how the events world works and find my way on site."
      },
      {
        "_id": "faq-voor-eventbureaus-5",
        "question": "Can you deliver same-day highlights for the client?",
        "answer": "Yes. Same-day delivery is available as an add-on. Ideal if your client wants content on social media immediately after the event."
      },
      {
        "_id": "faq-voor-eventbureaus-6",
        "question": "Do you also work outside the Netherlands?",
        "answer": "Yes. I work throughout the Netherlands and abroad on request. Travel costs are calculated separately."
      }
    ]
  },
  "voor-hotels": {
    "nl": [
      {
        "_id": "faq-voor-hotels-1",
        "question": "Waarom hebben wij als hotel content van echte events nodig?",
        "answer": "Lege zalen verkopen geen events. Authentieke beelden van echte congressen laten eventplanners zien wat jouw locatie kan als er mensen in de zaal zitten. Dat werkt sterker dan studiofoto's zonder publiek."
      },
      {
        "_id": "faq-voor-hotels-2",
        "question": "Moeten wij toestemming vragen aan de eventorganisator?",
        "answer": "Dat regelen we vooraf samen. In de meeste gevallen volstaat een korte melding aan de organisator. Ik werk altijd discreet en professioneel."
      },
      {
        "_id": "faq-voor-hotels-3",
        "question": "Hoe vaak kunnen we jullie inzetten?",
        "answer": "Dat bepaal je zelf. Per event schakelen kan, maar een vaste samenwerking bij terugkerende congressen geeft doorlopende marketingbeelden van je faciliteiten."
      },
      {
        "_id": "faq-voor-hotels-4",
        "question": "Mag de eventorganisator de content ook gebruiken?",
        "answer": "Dat bespreken we vooraf. Het is mogelijk om content te delen met beide partijen. In dat geval stemmen we de rechten en het gebruik af."
      },
      {
        "_id": "faq-voor-hotels-5",
        "question": "Leveren jullie ook video naast foto?",
        "answer": "Ja. Foto en video kunnen gecombineerd worden, zodat je voor website, social media en salesmateriaal het juiste formaat hebt."
      },
      {
        "_id": "faq-voor-hotels-6",
        "question": "Kunnen jullie ook onze lege vergaderzalen professioneel fotograferen?",
        "answer": "Onze focus ligt op events met publiek en sfeer. Voor lege zaalfoto's kun je beter een interieurfotograaf inschakelen. Tijdens echte events leg ik je ruimte op z'n best vast."
      }
    ],
    "en": [
      {
        "_id": "faq-voor-hotels-1",
        "question": "Why do we as a hotel need content from real events?",
        "answer": "Empty rooms do not sell events. Authentic visuals from real congresses show event planners what your venue can do with people in the room. That works better than studio shots without an audience."
      },
      {
        "_id": "faq-voor-hotels-2",
        "question": "Do we need permission from the event organiser?",
        "answer": "We arrange that together in advance. In most cases a brief notice to the organiser is sufficient. I always work discreetly and professionally."
      },
      {
        "_id": "faq-voor-hotels-3",
        "question": "How often can we use your services?",
        "answer": "That is up to you. Booking per event is possible, but a fixed partnership for recurring congresses provides ongoing marketing visuals of your facilities."
      },
      {
        "_id": "faq-voor-hotels-4",
        "question": "Can the event organiser also use the content?",
        "answer": "We discuss that in advance. It is possible to share content with both parties. In that case we agree on rights and usage."
      },
      {
        "_id": "faq-voor-hotels-5",
        "question": "Do you also deliver video in addition to photo?",
        "answer": "Yes. Photo and video can be combined, so you have the right format for your website, social media and sales materials."
      },
      {
        "_id": "faq-voor-hotels-6",
        "question": "Can you also photograph our empty meeting rooms professionally?",
        "answer": "Our focus is on events with audience and atmosphere. For empty room shots an interior photographer is a better fit. During real events I capture your space at its best."
      }
    ]
  },
  "voor-bedrijven": {
    "nl": [
      {
        "_id": "faq-voor-bedrijven-1",
        "question": "Wij organiseren één user conference per jaar. Is dat genoeg?",
        "answer": "Absoluut. Juist dan is het belangrijk dat je er alles uithaalt. Eén productiedag levert een contentbox waar je marketeer maanden mee vooruit kan: foto's, aftermovie, interviews en social cuts."
      },
      {
        "_id": "faq-voor-bedrijven-2",
        "question": "Onze marketeer heeft weinig tijd na het event. Hoe helpt Eventshoot.nl?",
        "answer": "Alle content wordt kant-en-klaar geleverd in de juiste formaten. Geen extra nabewerking nodig, direct te plaatsen op LinkedIn, je website en in je nieuwsbrief."
      },
      {
        "_id": "faq-voor-bedrijven-3",
        "question": "Kunnen jullie interviews met klanten of sprekers verzorgen?",
        "answer": "Ja. Het Headline-pakket bevat 10–15 interviews, Heroes 25–30. Handig voor testimonials, LinkedIn-posts en content voor je volgende editie."
      },
      {
        "_id": "faq-voor-bedrijven-4",
        "question": "Hoe ver van tevoren moeten we boeken?",
        "answer": "Zo vroeg mogelijk, zeker voor grote events. Neem contact op en we kijken wat de agenda toelaat. Last-minute kan soms ook."
      },
      {
        "_id": "faq-voor-bedrijven-5",
        "question": "Wat is het verschil tussen foto-only en een complete contentbox?",
        "answer": "Foto-only levert je beelden voor website en social. Een complete contentbox voegt aftermovie, interviews en meerdere social formaten toe. Bekijk de pakketten Highlight, Headline en Heroes op de tarievenpagina."
      },
      {
        "_id": "faq-voor-bedrijven-6",
        "question": "Kunnen we de content ook intern gebruiken?",
        "answer": "Ja. Foto's en video's zijn geschikt voor interne communicatie, onboarding, salespresentaties en je jaarverslag."
      }
    ],
    "en": [
      {
        "_id": "faq-voor-bedrijven-1",
        "question": "We organise one user conference per year. Is that enough?",
        "answer": "Absolutely. That is exactly when it matters to get everything out of it. One production day delivers a content box your marketing team can use for months: photos, aftermovie, interviews and social cuts."
      },
      {
        "_id": "faq-voor-bedrijven-2",
        "question": "Our marketer has little time after the event. How does Eventshoot.nl help?",
        "answer": "All content is delivered ready-to-use in the right formats. No extra editing needed, publish directly on LinkedIn, your website and in your newsletter."
      },
      {
        "_id": "faq-voor-bedrijven-3",
        "question": "Can you conduct interviews with customers or speakers?",
        "answer": "Yes. The Headline package includes 10–15 interviews, Heroes 25–30. Useful for testimonials, LinkedIn posts and content for your next edition."
      },
      {
        "_id": "faq-voor-bedrijven-4",
        "question": "How far in advance should we book?",
        "answer": "As early as possible, especially for large events. Get in touch and we check what the calendar allows. Last-minute is sometimes possible too."
      },
      {
        "_id": "faq-voor-bedrijven-5",
        "question": "What is the difference between photo-only and a complete content box?",
        "answer": "Photo-only gives you visuals for website and social. A complete content box adds aftermovie, interviews and multiple social formats. See the Highlight, Headline and Heroes packages on the pricing page."
      },
      {
        "_id": "faq-voor-bedrijven-6",
        "question": "Can we also use the content internally?",
        "answer": "Yes. Photos and videos are suitable for internal communications, onboarding, sales presentations and your annual report."
      }
    ]
  }
} as Record<FaqPageKey, FaqLangMap>
