// Auto-generated by scripts/generate-vodcast-photos.mjs — do not edit manually.
// Bron: public/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/ — wat in de map staat, komt op de pagina.

export const VODCAST_PHOTO_BASE = '/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST'

export const VODCAST_HERO = `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202570.jpg`
export const VODCAST_LONGFORM = `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/Vodcast_10.jpg`
export const VODCAST_SHORTFORM = `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/Vodcast_5.jpg`

export const VODCAST_GALLERY = [
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202420.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202423.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202426.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202428.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202517.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202542.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202572.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/RT202574.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/Vodcast_1.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/Vodcast_5.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/Vodcast_9.jpg`, altKey: 'altGallery' as const },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/VODCAST/Vodcast_10.jpg`, altKey: 'altGallery' as const },
]
