// Auto-generated by scripts/generate-werk-photos.mjs — do not edit manually.
// Bron: public/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/ — wat in de map staat, komt op /werk.

export const WERK_PHOTO_BASE = '/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS'

export const WERK_HERO = `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-57.jpg`

export const WERK_PHOTOS = [
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/OBEYA_Summit_26_6_2026-414.jpg`, alt: 'Eventfotografie congres Nederland' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/RT105620.jpg`, alt: 'Zakelijk evenement fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-84.jpg`, alt: 'Seminar fotograaf' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-104.jpg`, alt: 'Congres fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot_121.jpg`, alt: 'Professionele eventfotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/rolf_trijber_interview_2.jpg`, alt: 'Ledendag fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-70.jpg`, alt: 'Bedrijfsbijeenkomst fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-93.jpg`, alt: 'Congres spreker fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-91.jpg`, alt: 'Zakelijk event reportage' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-107.jpg`, alt: 'Netwerkbijeenkomst fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/DSR_SUMMIT_18_6_2026-75.jpg`, alt: 'Eventfotografie congres Nederland' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/PAS_DenHaag_5_10_26-195.jpg`, alt: 'Zakelijk evenement fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/DSR_SUMMIT_18_6_2026-99.jpg`, alt: 'Seminar fotograaf' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/PAS_DenHaag_5_10_26-125.jpg`, alt: 'Congres fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-97.jpg`, alt: 'Professionele eventfotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-50.jpg`, alt: 'Ledendag fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-57.jpg`, alt: 'Bedrijfsbijeenkomst fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-79.jpg`, alt: 'Congres spreker fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-90.jpg`, alt: 'Zakelijk event reportage' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-77.jpg`, alt: 'Netwerkbijeenkomst fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-101.jpg`, alt: 'Eventfotografie congres Nederland' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-53.jpg`, alt: 'Zakelijk evenement fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/RT105622.jpg`, alt: 'Seminar fotograaf' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-98.jpg`, alt: 'Congres fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/DSR_SUMMIT_18_6_2026-73.jpg`, alt: 'Professionele eventfotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-89.jpg`, alt: 'Ledendag fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/RT105613.jpg`, alt: 'Bedrijfsbijeenkomst fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-54.jpg`, alt: 'Congres spreker fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/PAS_DenHaag_5_10_26-151.jpg`, alt: 'Zakelijk event reportage' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-88.jpg`, alt: 'Netwerkbijeenkomst fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/PAS_DenHaag_5_10_26-257.jpg`, alt: 'Eventfotografie congres Nederland' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-87.jpg`, alt: 'Zakelijk evenement fotografie' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-96.jpg`, alt: 'Seminar fotograaf' },
  { src: `/DATA_EVENTSHOOT/SITE_IMAGES/EVENTFOTOS/eventshoot-60.jpg`, alt: 'Congres fotografie' },
]
